### ISSUE TITLE
Nothing happens with TODO files

### ISSUE THREAD

**Issue by JoeCianflone** [coddx-hq/coddx-alpha#1]
Just pulled this down a few moments ago, I'm using the latest version as of this writing.

I've got a markdown file called `TODO.md` that I created in the root of my project. Tried to look at the kanban board and it doesn't show anything and the `New Task` and nothing happened. 

I could be doing something wrong, but I'm not getting any errors so...?

My TODO.md file

```md
# Rebase Next Steps

- [ ] One
- [ ] Two

```

What is generated

<img width="665" alt="Screen Shot 2020-03-15 at 8 26 24 PM" src="https://user-images.githubusercontent.com/989648/76714081-86a4e780-66fb-11ea-836f-1575a642a31d.png">

**Comment by ngduc** [comment]
Hi @JoeCianflone Thanks for reporting.

This is an example of a generated TODO.md file:

```
# Project Rocket

Project Description

### Todo

- [ ] Task 1  

### In Progress

- [ ] Task 2  

### Done ✓

- [x] Completed Task    

```

can you delete your existing TODO.md file first, then open the Task Board? It will re-generate a new file. Sorry it's a bit strict about the text syntax and assumes certain things like: project title, column titles, task lines.

also pls upgrade the extension as I've just published a new version :)

**Comment by ngduc** [comment]
Edit: version 0.2.3 is available now :) Thanks.

**Comment by JoeCianflone** [comment]
Ah got it! Thank you it's working!
