### ISSUE TITLE
Remove checkboxes from the tasks

### ISSUE THREAD

**Issue by kikijiki** [coddx-hq/coddx-alpha#10]
You already have the task state represented in the columns (todo, in progress, done), the checkbox is redundant.

**Comment by ngduc** [comment]
The checkbox is there to make it compatible with [Github checklist syntax](https://help.github.com/en/github/managing-your-work-on-github/about-task-lists)

I will add a setting to support checkboxes or not.

**Comment by ngduc** [comment]
@kikijiki , now with v0.2.17+ checkboxes are optional (if your task titles don't have them). Let me know if that works for you. Thanks.

![image](https://user-images.githubusercontent.com/639189/77401920-03266e80-6d6b-11ea-89d2-8d9f796091b8.png)

**Comment by kikijiki** [comment]
Cool, thanks!
