### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by GotJimmy** [coddx-hq/coddx-alpha#12]
Please allow text and background colors to be set.

**Comment by GotJimmy** [comment]
That's how it looks right now:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/6039735/77810865-10a76580-7097-11ea-91c2-0552e1abe73c.png">

**Comment by ngduc** [comment]
@GotJimmy That looks like an old version.
The new version fixed that - https://github.com/coddx-hq/coddx-alpha/issues/5

Could you try to upgrade the extension?

**Comment by GotJimmy** [comment]
Ok but from where? I got this one from the VSCode extensions page.

**Comment by ngduc** [comment]
click on the left menu, then type "coddx", then click Install or Update/Upgrade:

![image](https://user-images.githubusercontent.com/639189/77811023-eb920300-7054-11ea-9fdf-0231e5e600c1.png)

**Comment by GotJimmy** [comment]
Ok did that. The problem seems to be that I'm using my own theming. With downloaded color themes it looks fine. What color tokens do you use?

**Comment by ngduc** [comment]
Nice. My favorite theme is Dracula Dark+ which is very similar to the default VSCode dark theme.

**Comment by ngduc** [comment]
color variables it's using:
```
tab-border
tab-inactiveBackground
button-text-color
tab-foreground
```

**Comment by GotJimmy** [comment]
Thanks for the info on the variables used. I'm using hex values with alpha (i.e. #0088ff44) but you seem to ignore the alpha value. That's why the backgrounds in my screenshot above are so dark.
May I suggest that you allow those 4 color variables to also be set in settings.json? And if the values are not set there you fall back to the values from the color theme. Just a thought.

**Comment by ngduc** [comment]
Yes, that's the plan. Thanks for your suggestions @GotJimmy !
