### ISSUE TITLE
Sub-folder support?

### ISSUE THREAD

**Issue by JasonSwindle** [coddx-hq/coddx-alpha#13]
It would be awesome to support TODO.md in the main folder and sub-folders. Many times, each folder can have a different TODO.

**Comment by ngduc** [comment]
@JasonSwindle This is already supported.
https://github.com/coddx-hq/coddx-alpha/blob/master/docs/task-board.md
(see "Setting" section to customize for multiple todo file paths)

**Comment by ngduc** [comment]
Closing this. Let me know if you still have this issue.

**Comment by JasonSwindle** [comment]
Howdy,

The main issue is, I have many folders that are dynamic, so adding and removing TODO paths becomes a great bother.  I would also love this to work inside notes too.  Many times I will have meetings with TODO items (each meeting is a unique note), and being able to use this awesome tool per markdown file would be great too.
