### ISSUE TITLE
Poor task font on windows

### ISSUE THREAD

**Issue by marektoman** [coddx-hq/coddx-alpha#16]
The task board uses a different font than the code editor or menus do. Is there a hardcoded name that is not available so it defaults to something nobody wants?

![image](https://user-images.githubusercontent.com/47689923/78580575-dfffc280-7832-11ea-869a-8e9038d143de.png)

**Comment by king-brave-github** [comment]
Same problem here! +1

**Comment by king-brave-github** [comment]
@marektoman, I have been trying to change the default font on my own but with no success. Did you find any workaround?

**Comment by marektoman** [comment]
@king-brave-github I stopped using the extension, so I did not try. Good luck.

**Comment by ngduc** [comment]
Now I have a Windows laptop.
Fixed in the latest version. Thanks for reporting.
