### ISSUE TITLE
Coddx associates to json files

### ISSUE THREAD

**Issue by ajcool2k** [coddx-hq/coddx-alpha#2]
Hi, promising project!

Looks like JSON files like package.json are associated with the dummy config. It seems to break syntax highlighting vscode usually provides. Is it intended?

**Comment by wrgrant** [comment]
Is there a manual workaround to this in the meantime?

**Comment by wrgrant** [comment]
This section seems to be the issue. 

Can `languages` be empty? I take it this was placeholder in a template `package.json`?

https://github.com/coddx-hq/coddx-alpha/blob/52c4604bb00a2a536035260dd110106121f79f92/package.json#L37

**Comment by ngduc** [comment]
Hi @ajcool2k , thanks for reporting.
yes it's a placeholder. I wonder why it breaks syntax highlighting. That "languages" is for setting the programming language which the extension supports. I'll dig into this more.
Please let me know if you know more about breaking syntax highlighting.

**Comment by ngduc** [comment]
Removed dummyconfig, 0.2.6 is available now, please let me know if it works @ajcool2k @wrgrant 
Thanks.

**Comment by wrgrant** [comment]
It looks like what is happening is your code defines a new 'language' called Dummy which associates to json files. Overwriting the default association.

https://code.visualstudio.com/docs/languages/identifiers

**Comment by wrgrant** [comment]
Nice! Will test.

**Comment by wrgrant** [comment]
Verified working 0.2.6. 
That was crazy fast. Thank you!
