### ISSUE TITLE
Pull Requests?

### ISSUE THREAD

**Issue by IsaacSomething** [coddx-hq/coddx-alpha#24]
Why are you closing off the code?

Anyone can see your code by just going to `%USERPROFILE%\. vscode\extensions`, its a bit odd that you would not allow for PR's. Its actually kinda suspicious.

**Comment by ngduc** [comment]
I'm going to clean up the code and push it here.
Will update this ticket here.

**Comment by IsaacSomething** [comment]
Its a really nice extension btw
