### ISSUE TITLE
Obsidian plugin [information]

### ISSUE THREAD

**Issue by dxcore35** [coddx-hq/coddx-alpha#30]
If you do same functionality but as www.obsidian.md plugin, your name will be famous :) The plugin API will open when version 1 is released. Your tool is really great, unfortunately I don't use VStudio. I think many non coders will benefit from your tool if it is usable outside of VStudio! Thanks

**Comment by ngduc** [comment]
Yes, I agree. Thanks for your idea.
I plan to create something that works outside VSCode, maybe a portable web/desktop PWA app.
This will be a project by itself.

**Comment by dxcore35** [comment]
It is already done.
