### ISSUE TITLE
Watch for modify sections in TODO.md file

### ISSUE THREAD

**Issue by wrgrant** [coddx-hq/coddx-alpha#4]
When I add / reorder sections in the TODO file, the sections are not redrawn in the Task Board until it's closed and reopened.

**Comment by ngduc** [comment]
v0.2.17+ now has the Refresh button next to the project name.
After editing your TODO file, just click that button to reload the latest content.

**Comment by ngduc** [comment]
Closing this. I will look into 2-way syncing methods separately but it may introduce more complexity.
