### ISSUE TITLE
Respect VSCode theme

### ISSUE THREAD

**Issue by wrgrant** [coddx-hq/coddx-alpha#5]
Looks right for dark theme. Strange with light theme.

Can't upload gif for some reason.

**Comment by ngduc** [comment]
Thanks. This is coming very soon.

**Comment by ngduc** [comment]
v0.2.27 now uses vscode theme colors:

![image](https://user-images.githubusercontent.com/639189/77737711-c2796000-6fcb-11ea-98fc-4da722ae201d.png)

cc @wrgrant @markdall
