### ISSUE TITLE
Add custom project name to TODO.md

### ISSUE THREAD

**Issue by Dunni3** [coddx-hq/coddx-alpha#6]
You should be able to change "Project Name" at the top of `TODO.md`

Currently, if I change the first line of `TODO.md`, it is not updated in the task board. When I make any changes to the task board, the first line of `TODO.md` is reset.

**Comment by ngduc** [comment]
It can be changed. Just reopen the Task Board after changing & saving TODO.md

**Comment by ngduc** [comment]
Closing this. Please feel free to reopen if there is anything.
