### ISSUE TITLE
Allow a global TODO.md file

### ISSUE THREAD

**Issue by sbruce** [coddx-hq/coddx-alpha#9]
It would be nice if you could specify a path to a single, generic `TODO.md` file in `settings.json`.

This could let coddx function as a more generic task management system.

Sample `settings.json` file:
```json
{
   "coddx.use_generic_todo_md": true,
   "coddx.todo_md_path": "path to the TODO.md file"
}
```

**Comment by katiawheeler** [comment]
+1 to this - I'd like a global one as well. Often I'm in multiple repos and code bases to accomplish one task.

**Comment by ngduc** [comment]
This will be released shortly:

![image](https://user-images.githubusercontent.com/639189/77383324-d872f080-6d3f-11ea-8bae-3e4af90cbe78.png)

@sbruce @katiawheeler

**Comment by ngduc** [comment]
v0.2.15 is available now. Let me know if it works. Thanks.

**Comment by katiawheeler** [comment]
This is great! Thanks @ngduc!

**Comment by sbruce** [comment]
Thanks! @ngduc
